# Generated by Django 5.0 on 2024-12-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_saved_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('Cooking', 'Cooking'), ('Sport', 'Sport'), ('Computer Science', 'Computer Science'), ('Art', 'Art'), ('Entertainment', 'Entertainment'), ('School', 'School'), ('General', 'General'), ('Other', 'Other')], default='General', max_length=50),
        ),
    ]
